### ISSUE TITLE
Can't Install anything.. To do with electron

### ISSUE THREAD

**Issue by Bigmanted** [yeeezy/splash-party#14]
Whenever I have tried to install yeezy splash.
I have tried to do 'NPM cache clean' and then a reinstall.

`C:\Users\Admin\splash-party-master\node_modules\electron\install.js:47
  throw err
  ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\Admin\splash-party-master\node_modules\electron\dist\resources'
    at Error (native)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Admin\splash-party-master\npm-debug.log`

**Comment by ghost** [comment]
1. Start with a fresh install of Splash Party by deleting the existing files, downloading again and extracting.
2. Open up the "package.json" file in the splash-party-master folder with Notepad++.
3. Edit the `"devDependencies": {},` line of code to say: `  "devDependencies": {
	"extract-zip": "=1.6.0"
  },` (you can just copy and paste, don't fuck up indentation)
4. Run in terminal/command prompt again and type `npm install`. The program should compile correctly and function as expected.

**Comment by Bigmanted** [comment]
Hey man, It still has the same issue.
http://i.imgur.com/UMhauwh.png

Tried it all :(

**Comment by Bigmanted** [comment]
> Start with a fresh install of Splash Party by deleting the existing files, downloading again and extracting.
> Open up the "package.json" file in the splash-party-master folder with Notepad++.
> Edit the "devDependencies": {}, line of code to say: "devDependencies": { "extract-zip": "=1.6.0" }, (you can just copy and paste, don't fuck up indentation)
> Run in terminal/command prompt again and type npm install. The program should compile correctly and function as expected.

Hello, Thanks for the speedy reply.

It appears that it still does not work.
http://i.imgur.com/UMhauwh.png

Please advise :(

**Comment by ghost** [comment]
Please provide me with the `C:\Users\Admin\splash-party-master\npm-debug.log` file.

**Comment by Bigmanted** [comment]
> Please provide me with the C:\Users\Admin\splash-party-master\npm-debug.log file.

Thanks for the reply, Is there any way I can contact you quicker ? I will supply it in a few hours.

**Comment by Bigmanted** [comment]
> Please provide me with the C:\Users\Admin\splash-party-master\npm-debug.log file.

you're a god, I downloaded the file you made, and it works now. I must have done it wrong!
