### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by LittlexDylan** [yeeezy/splash-party#5]
Can someone make a tutorial of this?

**Comment by 0xhjohnson** [comment]
You don't really need one he explains everything in the README.md in great detail

**Comment by TazJam88** [comment]
I'm struggling to understand the instructions. Hopefully someone will make a video on how to.

**Comment by adipy01101** [comment]
really is straight forward and to the point.. no video necessary

**Comment by adipy01101** [comment]
Straight forward and easy to follow directions.. No video necessary

**Comment by meesg** [comment]
Mac : https://www.youtube.com/watch?v=eFeYAOPhkpE
Windows : https://www.youtube.com/watch?v=73EFtLyR5Ak
There is not really much to it.

**Comment by danimal1124** [comment]
i made the video on how to install and hope it helped. im jsut needing help on how to actually use splash party properly. like how do i run the splash page when there is one and how do i set it to where all the new electron tabs that pop up go to the lets say the alexander wang splash page. another thing was if one of the electron windows were to pash plash can i just chekcout through that window and if not how do i transfer it to chrome or use /// to checkout. one last thing i had a question on was how do i make it to where the electron windows pop up faster if i have nay control over it that is.

**Comment by meesg** [comment]
What exactly do you mean with "how do I run the splash page"? If you mean how to start splash party (considering you have it set up already), all you have to do is start CMD (command window) with shift right click in the folder and type "node app". Before starting splash party you have to make sure that your configuration file is set. In the config.json file set splashUrl to the URL of the waiting room (http://www.adidas.com/yeezy for example) and set splashUniqueIdentifier to something in the html that only exist on the splash page (if you have to change it someone on reddit will probably mention it in the thread). You can tweak the other variables as wanted, but this isn't necessary. The pages that pop up will go to the page where you can add the product to your cart. Yes, it is probably possible checkout through electron. A high partySize and low waitTime will probably help a session passing the splash faster.

**Comment by yeeezy** [comment]
please continue this subject if needed in the subreddit
