### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Jeisonx** [yeeezy/splash-party#6]
Can it be possible to add a space between each cookie session, to save a lil time on copy and paste.
<img width="1194" alt="screen shot 2017-03-04 at 8 26 46 pm" src="https://cloud.githubusercontent.com/assets/22186712/23583671/70b87fea-0119-11e7-81a3-e2151d1a3187.png">

**Comment by yeeezy** [comment]
Cookie printing will be much better, updating the code later today. I'll close the issue after I update

**Comment by yeeezy** [comment]
cookie printing is now in proper json format, for easy import
