### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by GAWDTHREADS** [yeeezy/splash-party#9]
Add multiple proxy support

**Comment by yeeezy** [comment]
This project started as a proxyless version of https://github.com/yzyio/adidas-multi-session

You should use that script if you're interested in proxies.

Other than that, known proxy providers can always be blocked, while home IPs have a way lower chance of being blocked (even running 100 threads of splash-party won't get you banned)

So I prefer a proxyless solution
